name: Quarkus Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: quarkusio/quarkus@master
      - uses: actions/setup-java@v1
        with:
          java-version: 19
      - run: quarkus build
